name: Akses Terminal Linux GitHub
on: [push]
jobs:
  akses-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Menyiapkan Folder Project
        uses: actions/checkout@v4

      - name: Mael-akses-linuxxx
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

